CREATE TABLE public.comment (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    comment_text TEXT NOT NULL,
    comment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,

    CONSTRAINT fk_account
        FOREIGN KEY (account_id)
        REFERENCES account (account_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_inventory
        FOREIGN KEY (inv_id)
        REFERENCES inventory (inv_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_comment_inv_id ON public.comment (inv_id);
